sudo: required

services:
  - docker

language: java

jdk:
  - oraclejdk8
  - oraclejdk11
  - openjdk10
  - openjdk11

env:
  matrix:
   - RC_VERSION=latest
   - RC_VERSION=develop
   - RC_VERSION=2.4.7
   - RC_VERSION=2.3.3
   - RC_VERSION=2.2.1
   - RC_VERSION=2.1.3
   - RC_VERSION=2.0.0
   - RC_VERSION=1.3.2
   - RC_VERSION=1.2.1
   - RC_VERSION=1.1.3
   - RC_VERSION=1.0.3
   - RC_VERSION=0.74.3
   - RC_VERSION=0.73.2
   - RC_VERSION=0.72.3
   - RC_VERSION=0.71.2
   - RC_VERSION=0.70.4
   - RC_VERSION=0.69.2
   - RC_VERSION=0.68.5
   - RC_VERSION=0.67.0
   - RC_VERSION=0.66.3
   - RC_VERSION=0.65.2
   - RC_VERSION=0.64.2
   - RC_VERSION=0.63.3
   - RC_VERSION=0.64.1
   - RC_VERSION=0.63.3
   - RC_VERSION=0.62.2
   - RC_VERSION=0.61.2
   - RC_VERSION=0.60.2
   - RC_VERSION=0.59.6
   - RC_VERSION=0.58.4
   - RC_VERSION=0.57.4
   - RC_VERSION=0.56.0
   - RC_VERSION=0.55.1
   - RC_VERSION=0.54.2
   - RC_VERSION=0.53.0
   - RC_VERSION=0.52.0

script:
  - mvn clean package --quiet
  - .bin/docker-build-images.sh && .bin/docker-run.sh
  - travis_retry mvn -Pdocker -Djava.awt.headless=true -Dmaven.test.redirectTestOutputToFile=true -Dcobertura.report.format=xml --fail-at-end --batch-mode cobertura:cobertura verify

cache:
  directories:
  - ~/.m2

after_success:
  - cobertura:dump-datafile
  - bash <(curl -s https://codecov.io/bash)


install:
  -
