sudo: required

services:
  - docker

language: java

env:
  matrix:
   - RC_VERSION=latest
   - RC_VERSION=0.51.0
   - RC_VERSION=0.50.1
   - RC_VERSION=0.50.0
   - RC_VERSION=0.49.3
   - RC_VERSION=0.49.3
   - RC_VERSION=0.49.2
   - RC_VERSION=0.49.1
   - RC_VERSION=0.49.0
   - RC_VERSION=0.48.2
   - RC_VERSION=0.48.1
   - RC_VERSION=0.48.0
   - RC_VERSION=0.47.1
   - RC_VERSION=0.46.0
   - RC_VERSION=0.45.0
   - RC_VERSION=0.44.0
   - RC_VERSION=0.43.0
   - RC_VERSION=0.42.0

script:
  - mvn clean package --quiet
  - mvn -Pdocker verify -Drocket.version=$RC_VERSION

cache:
  directories:
  - ~/.m2

branches:
  only:
    - master

install:
  -

