version: '2.1'
services:

  db:
    container_name: mongo_db
    image: mongo:latest
    environment:
      - MONGO_PORT
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:${MONGO_PORT}"]
        interval: 30s
        timeout: 10s
        retries: 5

  rocketchat:
    container_name: rocketchat
    image: rocketchat/rocket.chat:${RC_VERSION}
    environment:
      - RC_VERSION
      - RC_PORT
      - MONGO_URL
      - HOME
      - PORT
      - ROOT_URL
      - Accounts_AvatarStorePath
      - ADMIN_USERNAME
      - ADMIN_PASS
      - ADMIN_EMAIL
    depends_on:
      - db
    links:
      - db
    ports:
      - "${RC_PORT}:${RC_PORT}"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:${RC_PORT}"]
        interval: 30s
        timeout: 30s
        retries: 5
