ports:
  - ${rocket.port}
# containers that this should be linked to, started before this one and stopped afterwards
links:
  - mongo:mongo
healthChecks:
  pings:
    - url: http://localhost:${rocket.port}/
      timeout: 60000
tag: jenkins-plugin/${project.artifactId}-rocket:${project.version}
